version: '3'

volumes:
  cookies: {}
  screenshots: {}
  minio_data: {}
  minio_config: {}

services:
  crawler:
    image: windyakin/aq0urs-club
    build: .
    cap_add:
      - SYS_ADMIN
    env_file: .env
    environment:
      - TZ=Asia/Tokyo
      - PUPPETEER_TIMEOUT=90000
    volumes:
      - cookies:/usr/src/app/cookie
      - screenshots:/usr/src/app/screenshot
  minio:
    image: minio/minio
    ports:
      - 9000:9000
    env_file: .env
    volumes:
      - minio_data:/data
      - minio_config:/root/.minio
    entrypoint:
      - sh
      - -c
    command: '"mkdir -p /data/${MINIO_BUCKET_NAME} && /usr/bin/docker-entrypoint.sh server /data"'
