name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  docker_image_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platforms:
          - linux/amd64
          - linux/arm64
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3

      - uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          tags: windyakin/aq0urs-club:latest
          push: false

  eslint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 16.x
          - 18.x
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install

      - run: npm run lint
