name: Docker Image CI

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker Image
        uses: actions/docker/cli@master
        with:
          args: build --pull --no-cache . -f Dockerfile
