name: Publish to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker Image
        uses: actions/docker/cli@master
        with:
          args: build --pull --no-cache . -f Dockerfile --tag windyakin/aq0urs-club:latest
      - uses: actions/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish to Docker Hub
        uses: actions/docker/cli@master
        with:
          args: push windyakin/aq0urs-club:latest
