name: Publish to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build the Docker Image
        run: docker build --pull --no-cache -f Dockerfile --tag windyakin/aq0urs-club:latest --tag ghcr.io/windyakin/aq0urs-club:latest .

      - name: Login to the Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish to Docker Hub
        run: docker push windyakin/aq0urs-club:latest

      - name: Login to the GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Publish to GitHub Container Registry
        run: docker push ghcr.io/windyakin/aq0urs-club:latest
