name: Publish to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build the Docker Image
        run: docker build --pull --no-cache . -f Dockerfile --tag windyakin/aq0urs-club:latest

      - name: Login to the Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "${DOCKER_PASSWORD}" | docker login -u ${DOCKER_USERNAME} --password-stdin

      - name: Publish to Docker Hub
        run: docker push windyakin/aq0urs-club:latest
